name: Codepush-Android-TEST
on:
  push:
    tags:
      - Codepush-Android-[0-9]+/v[0-9]+.[0-9]+.[0-9]+
jobs:
  getversion:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      target_version: ${{ steps.get_target_version.outputs.target_version }}
    steps:
      - name: Get current tag
        id: ctag
        run: |
          echo "${GITHUB_REF#refs/*/}"
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - uses: jungwinter/split@v2
        id: split_tag
        with:
          msg: ${{ steps.ctag.outputs.tag }}
          separator: /v
      - name: Get target_version
        id: get_target_version
        env:
          TAG_VER: ${{steps.split_tag.outputs._1}}
        run: |
          echo "target_version=$TAG_VER" >> $GITHUB_OUTPUT
  update-android:
    name: Update Android
    needs: getversion
    runs-on: ubuntu-latest
    steps:
      - name: Show target_version
        run: echo ${{needs.getversion.outputs.target_version}}