name: Codepush-Android-TEST

on:
  push:
    # branches:
    #   - codepush-android
    tags:
      - 'CP-Android/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  getversion:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
    # 'prepare'  to get output variable from future step
      target_version: ${{ steps.setoutput.outputs.target_version }}

    steps:

      - name: Get current tag
        id: ctag
        run: |
          echo "${GITHUB_REF#refs/*/}"
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - uses: jungwinter/split@v2
        id: stag
        with:
          msg: ${{ steps.ctag.outputs.tag }}
          separator: "/v"

      - name: Set Output 
        id: setoutput
        env:
          TAG_VER: ${{steps.stag.outputs._1}}
        run: |
          echo ${{steps.splittag.outputs}}
          echo "target_version=$TAG_VER" >> $GITHUB_OUTPUT


  update-android:
    name: Update Android
    needs: getversion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Show target_version
        run: echo ${{needs.getversion.outputs.target_version}} 

      - name: Show branch name
        run: cat test.txt